export const GET_MOVIES_TRENDING_REQUESTED = 'GET_MOVIES_TRENDING_REQUESTED';
export const GET_MOVIES_TRENDING_SUCCESS = 'GET_MOVIES_TRENDING_SUCCESS';
export const GET_MOVIES_TRENDING_FAILED = 'GET_MOVIES_TRENDING_FAILED';

export const GET_SEARCH_DATA_REQUESTED = 'GET_SEARCH_DATA_REQUESTED';
export const GET_SEARCH_DATA_SUCCESS = 'GET_SEARCH_DATA_SUCCESS';
export const GET_SEARCH_DATA_FAILED = 'GET_SEARCH_DATA_FAILED';
